def saveCard18(self):
    print("Save 18")

def saveCard9(self):
    print("Save 9")

def clearCard9(self):
    print(("Clear 9"))
    self.cmb_club_1_9.clear()
    self.cmb_club_2_9.clear()
    self.cmb_club_3_9.clear()
    self.cmb_club_4_9.clear()
    self.cmb_club_5_9.clear()
    self.cmb_club_6_9.clear()
    self.cmb_club_7_9.clear()
    self.cmb_club_8_9.clear()
    self.cmb_club_9_9.clear()

    self.cmb_hole_1_9.clear()
    self.cmb_hole_2_9.clear()
    self.cmb_hole_3_9.clear()
    self.cmb_hole_4_9.clear()
    self.cmb_hole_5_9.clear()
    self.cmb_hole_6_9.clear()
    self.cmb_hole_7_9.clear()
    self.cmb_hole_8_9.clear()
    self.cmb_hole_9_9.clear()

def clearCard18(self):
    print("Clear 18")
    self.cmb_club_1.clear()
    self.cmb_club_2.clear()
    self.cmb_club_3.clear()
    self.cmb_club_4.clear()
    self.cmb_club_5.clear()
    self.cmb_club_6.clear()
    self.cmb_club_7.clear()
    self.cmb_club_8.clear()
    self.cmb_club_9.clear()
    self.cmb_club_10.clear()
    self.cmb_club_11.clear()
    self.cmb_club_12.clear()
    self.cmb_club_13.clear()
    self.cmb_club_14.clear()
    self.cmb_club_15.clear()
    self.cmb_club_16.clear()
    self.cmb_club_17.clear()
    self.cmb_club_18.clear()

    self.cmb_hole_1.clear()
    self.cmb_hole_2.clear()
    self.cmb_hole_3.clear()
    self.cmb_hole_4.clear()
    self.cmb_hole_5.clear()
    self.cmb_hole_6.clear()
    self.cmb_hole_7.clear()
    self.cmb_hole_8.clear()
    self.cmb_hole_9.clear()
    self.cmb_hole_10.clear()
    self.cmb_hole_11.clear()
    self.cmb_hole_12.clear()
    self.cmb_hole_13.clear()
    self.cmb_hole_14.clear()
    self.cmb_hole_15.clear()
    self.cmb_hole_16.clear()
    self.cmb_hole_17.clear()
    self.cmb_hole_18.clear()